### ISSUE TITLE
Implementar 3 técnicas de segmentação

### ISSUE THREAD

**Issue by EmersonVeras** [EmersonVeras/atlanticoAcademy_Squad_1#18]
Implementar 3 técnicas de segmentação e aplicar nos 20 exemplos com padrão ouro definido.

**Comment by felipe-araujo** [comment]
kmeans
# See https://www.analyticsvidhya.com/blog/2019/04/introduction-image-segmentation-techniques-python/

otsu
# See https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_thresholding.html#sphx-glr-auto-examples-segmentation-plot-thresholding-py
chan vese
# Reference docs: https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_chan_vese.html

ver o arquivo generate_metrics.py
